repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests>=2.32.4
          - types-PyYAML>=6.0.12

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.393
    hooks:
      - id: pyright

  - repo: https://github.com/netromdk/vermin
    rev: v1.6.0
    hooks:
      - id: vermin
        args: [--target=3.9-, --violations]
