-- Create a view of NAV_BASE and FIX_BASE that combines some columns common to the two tables
CREATE VIEW WP_BASE AS
SELECT EFF_DATE, NAV_ID AS WP_ID, NAV_TYPE AS WP_TYPE, STATE_CODE, COUNTRY_CODE, LAT_DEG, LAT_MIN, LAT_SEC, LAT_HEMIS, LAT_DECIMAL, LONG_DEG, LONG_MIN, LONG_SEC, LONG_HEMIS, LONG_DECIMAL, HIGH_ALT_ARTCC_ID AS ARTCC_ID_HIGH, LOW_ALT_ARTCC_ID AS ARTCC_ID_LOW, PITCH_FLAG, CATCH_FLAG, SUA_ATCAA_FLAG
FROM NAV_BASE
UNION
SELECT EFF_DATE, FIX_ID AS WP_ID, FIX_USE_CODE AS WP_TYPE, STATE_CODE, COUNTRY_CODE, LAT_DEG, LAT_MIN, LAT_SEC, LAT_HEMIS, LAT_DECIMAL, LONG_DEG, LONG_MIN, LONG_SEC, LONG_HEMIS, LONG_DECIMAL, ARTCC_ID_HIGH, ARTCC_ID_LOW, PITCH_FLAG, CATCH_FLAG, SUA_ATCAA_FLAG
FROM FIX_BASE;

-- Add the latitude and longitude of the FROM_POINT to the AWY_SEG_ALT table, could be either a navaid or a fix
ALTER TABLE AWY_SEG_ALT ADD COLUMN LAT_DECIMAL REAL;
ALTER TABLE AWY_SEG_ALT ADD COLUMN LONG_DECIMAL REAL;
WITH COORDS AS (
    SELECT
        AWY_SEG_ALT.rowid,
        WP_BASE.LAT_DECIMAL,
        WP_BASE.LONG_DECIMAL
    FROM AWY_SEG_ALT
    LEFT JOIN WP_BASE ON
        AWY_SEG_ALT.FROM_POINT = WP_BASE.WP_ID AND
        AWY_SEG_ALT.FROM_PT_TYPE = WP_BASE.WP_TYPE AND
        AWY_SEG_ALT.COUNTRY_CODE = WP_BASE.COUNTRY_CODE
) UPDATE AWY_SEG_ALT SET LAT_DECIMAL = COORDS.LAT_DECIMAL, LONG_DECIMAL = COORDS.LONG_DECIMAL FROM COORDS WHERE AWY_SEG_ALT.rowid = COORDS.rowid;

-- Add the latitude and longitude of the POINT to the DP_RTE table, could be either a navaid or a fix
ALTER TABLE DP_RTE ADD COLUMN LAT_DECIMAL REAL;
ALTER TABLE DP_RTE ADD COLUMN LONG_DECIMAL REAL;
WITH COORDS AS (
    SELECT
        DP_RTE.rowid,
        WP_BASE.LAT_DECIMAL,
        WP_BASE.LONG_DECIMAL
    FROM DP_RTE
    LEFT JOIN WP_BASE ON
        DP_RTE.POINT = WP_BASE.WP_ID AND
        DP_RTE.POINT_TYPE = WP_BASE.WP_TYPE
) UPDATE DP_RTE SET LAT_DECIMAL = COORDS.LAT_DECIMAL, LONG_DECIMAL = COORDS.LONG_DECIMAL FROM COORDS WHERE DP_RTE.rowid = COORDS.rowid;

-- Add the latitude and longitude of the POINT to the STAR_RTE table, could be either a navaid or a fix
ALTER TABLE STAR_RTE ADD COLUMN LAT_DECIMAL REAL;
ALTER TABLE STAR_RTE ADD COLUMN LONG_DECIMAL REAL;
WITH COORDS AS (
    SELECT
        STAR_RTE.rowid,
        WP_BASE.LAT_DECIMAL,
        WP_BASE.LONG_DECIMAL
    FROM STAR_RTE
    LEFT JOIN WP_BASE ON
        STAR_RTE.POINT = WP_BASE.WP_ID AND
        STAR_RTE.POINT_TYPE = WP_BASE.WP_TYPE
) UPDATE STAR_RTE SET LAT_DECIMAL = COORDS.LAT_DECIMAL, LONG_DECIMAL = COORDS.LONG_DECIMAL FROM COORDS WHERE STAR_RTE.rowid = COORDS.rowid;

-- Add line sequence numbers to the AWY_SEG_ALT table, incrementing whenever a gap is found
ALTER TABLE AWY_SEG_ALT ADD COLUMN LINE_SEQ INTEGER;
WITH SEGMENTS AS (
    SELECT rowid,
        COUNT(CASE WHEN AWY_SEG_GAP_FLAG="Y" THEN 1 END)
        OVER (PARTITION BY AWY_LOCATION,AWY_ID ORDER BY POINT_SEQ ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) + 1
        AS LINE_SEQ
    FROM AWY_SEG_ALT
) UPDATE AWY_SEG_ALT SET LINE_SEQ = SEGMENTS.LINE_SEQ FROM SEGMENTS WHERE AWY_SEG_ALT.rowid = SEGMENTS.rowid;

-- Convert DD-MM-SS.SSSSH notation in MAA_BASE to decimal degrees
ALTER TABLE MAA_BASE ADD COLUMN LAT_DECIMAL REAL;
ALTER TABLE MAA_BASE ADD COLUMN LONG_DECIMAL REAL;
WITH COORDS AS (
    SELECT
        MAA_BASE.rowid,
        (CASE WHEN LATITUDE IS NULL THEN NULL ELSE (CASE WHEN SUBSTR(LATITUDE, -1) = 'N' THEN 1 ELSE -1 END) * (CAST(SUBSTR(LATITUDE, 1, 2) AS REAL) + CAST(SUBSTR(LATITUDE, 4, 2) AS REAL) / 60 + CAST(SUBSTR(LATITUDE, 7, 7) AS REAL) / 3600) END) AS LAT_DECIMAL,
        (CASE WHEN LONGITUDE IS NULL THEN NULL ELSE (CASE WHEN SUBSTR(LONGITUDE, -1) = 'E' THEN 1 ELSE -1 END) * (CAST(SUBSTR(LONGITUDE, 1, 3) AS REAL) + CAST(SUBSTR(LONGITUDE, 5, 2) AS REAL) / 60 + CAST(SUBSTR(LONGITUDE, 8, 7) AS REAL) / 3600) END) AS LONG_DECIMAL
    FROM MAA_BASE
) UPDATE MAA_BASE SET LAT_DECIMAL = COORDS.LAT_DECIMAL, LONG_DECIMAL = COORDS.LONG_DECIMAL FROM COORDS WHERE MAA_BASE.rowid = COORDS.rowid;

-- Convert DD-MM-SS.SSSSH notation in MAA_SHP to decimal degrees
ALTER TABLE MAA_SHP ADD COLUMN LAT_DECIMAL REAL;
ALTER TABLE MAA_SHP ADD COLUMN LONG_DECIMAL REAL;
WITH COORDS AS (
    SELECT
        MAA_SHP.rowid,
        (CASE WHEN LATITUDE IS NULL THEN NULL ELSE (CASE WHEN SUBSTR(LATITUDE, -1) = 'N' THEN 1 ELSE -1 END) * (CAST(SUBSTR(LATITUDE, 1, 2) AS REAL) + CAST(SUBSTR(LATITUDE, 4, 2) AS REAL) / 60 + CAST(SUBSTR(LATITUDE, 7, 7) AS REAL) / 3600) END) AS LAT_DECIMAL,
        (CASE WHEN LONGITUDE IS NULL THEN NULL ELSE (CASE WHEN SUBSTR(LONGITUDE, -1) = 'E' THEN 1 ELSE -1 END) * (CAST(SUBSTR(LONGITUDE, 1, 3) AS REAL) + CAST(SUBSTR(LONGITUDE, 5, 2) AS REAL) / 60 + CAST(SUBSTR(LONGITUDE, 8, 7) AS REAL) / 3600) END) AS LONG_DECIMAL
    FROM MAA_SHP
) UPDATE MAA_SHP SET LAT_DECIMAL = COORDS.LAT_DECIMAL, LONG_DECIMAL = COORDS.LONG_DECIMAL FROM COORDS WHERE MAA_SHP.rowid = COORDS.rowid;

-- Create tables for connected segment data
CREATE TABLE AWY_LINES AS SELECT DISTINCT AWY_LOCATION, AWY_ID, LINE_SEQ, GROUP_CONCAT(FROM_POINT ORDER BY POINT_SEQ) AS WPT_IDS FROM AWY_SEG_ALT GROUP BY AWY_LOCATION, AWY_ID, LINE_SEQ;
CREATE TABLE DP_LINES AS SELECT DISTINCT DP_COMPUTER_CODE, ROUTE_NAME, BODY_SEQ, GROUP_CONCAT(POINT ORDER BY POINT_SEQ) AS WPT_IDS FROM DP_RTE GROUP BY DP_COMPUTER_CODE, ROUTE_NAME, BODY_SEQ;
CREATE TABLE MTR_LINES AS SELECT DISTINCT ROUTE_TYPE_CODE, ROUTE_ID, GROUP_CONCAT(ROUTE_PT_ID ORDER BY ROUTE_PT_SEQ) AS ROUTE_IDS FROM MTR_PT GROUP BY ROUTE_TYPE_CODE, ROUTE_ID;
CREATE TABLE STAR_LINES AS SELECT DISTINCT STAR_COMPUTER_CODE, ROUTE_NAME, BODY_SEQ, GROUP_CONCAT(POINT ORDER BY POINT_SEQ) AS WPT_IDS FROM STAR_RTE GROUP BY STAR_COMPUTER_CODE, ROUTE_NAME, BODY_SEQ;
